export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const CHANGE_CURRENCY = 'CHANGE_CURRENCY';

export const SELECT_ATTRIBUTE = 'SECLECT_ATTRIBUTE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CART_TOGGLE = 'CART_TOGGLE';
export const CHANGE_RATES = 'CHANGE_RATES';

export const TOGGLE_PRODUCT = 'TOGGLE_PRODUCT';
export const CHANGE_CUR = 'CHANGE_CUR'
 